[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nw-checker"
version = "0.0.0"
description = "Network vulnerability checker"
requires-python = ">=3.11"
