name: CI (Hard)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: hard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Python+Flutter（not fastapi）を厳格モードで
  ci-hard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: |
          if [ -f nw_checker/pubspec.yaml ]; then cd nw_checker && flutter pub get; fi

      - name: Run unified tests (HARD)
        run: bash codex_run_tests.sh
        env:
          SOFT_CL: "0"          # ← ハードモード（lint/type/coverageでfail）
          PY_MIN_COV: "90"
          FL_MIN_LINE_RATE: "90.0"

  # fastapi テストは本番ゲートでも必須合格
  fastapi-hard:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run FastAPI tests
        run: pytest -m fastapi -vv
