name: CI (Hard)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci-hard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U pip && pip install -r requirements.txt -r requirements-dev.txt
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: cd nw_checker && flutter pub get
      - name: Run unified tests (HARD)
        run: bash codex_run_tests.sh
        env:
          SOFT_CL: "0"
          PY_MIN_COV: "90"
          FL_MIN_LINE_RATE: "90.0"
