name: CI

on:
  push:
    paths:
      - 'nw_checker/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    paths:
      - 'nw_checker/**'
      - '.github/workflows/flutter-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter:
    name: Flutter テスト
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check flutter files
        id: check_fl
        run: |
          if [ -f nw_checker/pubspec.yaml ]; then echo "exists=true" >> "$GITHUB_OUTPUT"; else echo "exists=false" >> "$GITHUB_OUTPUT"; fi

      - uses: flutter-actions/setup-flutter@v2
        if: ${{ steps.check_fl.outputs.exists == 'true' }}
        with:
          channel: 'stable'

      - name: Flutter version
        if: ${{ steps.check_fl.outputs.exists == 'true' }}
        run: flutter --version

      - name: Flutter pub get
        if: ${{ steps.check_fl.outputs.exists == 'true' }}
        working-directory: nw_checker
        run: flutter pub get

      - name: Run flutter tests
        if: ${{ steps.check_fl.outputs.exists == 'true' }}
        working-directory: nw_checker
        run: flutter test -r expanded

      - name: Note when skipped
        if: ${{ steps.check_fl.outputs.exists != 'true' }}
        run: |
          echo 'Flutter: skipped (no nw_checker/pubspec.yaml)'
