name: Python CI

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'pytest.ini'
      - '.github/workflows/python-ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'pytest.ini'
      - '.github/workflows/python-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run ruff
        run: ruff src tests
      - name: Run black --check
        run: black --check src tests
      - name: Run mypy
        run: mypy src
      - name: Run unit tests with coverage (gate)
        shell: bash
        run: |
          pytest -m "not fastapi and not slow" --cov=src --cov-report=term --cov-fail-under=80 -vv

  python-fastapi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install "fastapi[all]" uvicorn httpx pytest-asyncio
      - name: Run FastAPI tests
        run: pytest -m fastapi -vv
